name: CI
on:
  push:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  appstream-validate:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Install appstream
        run: |
          sudo apt-get update
          sudo apt-get install -y appstream

      - name: Validate metainfo
        run: |
          appstreamcli validate --strict --pedantic --explain org.DolphinEmu.dolphin-emu.metainfo.xml
